### PR TITLE
Change nuisances to nuances

### PR DESCRIPTION
**Pull request by dancingpixels**
Edited  _understanding the **nuances** of your app’s domain and more._
Changed Understand the *nuisances* of the app you're building to Understand the *nuisances* of the app you're building.

### CODE REVIEW

**Comment by nickjj** [comment]
Hi,

Thanks for the PR.

Would you mind amending this commit to also include fixing the 2nd typo of the same word? It's repeated near the top of the episode in the recap for this part of the sentence `understanding the nuisances`.

**Comment by nickjj** [comment]
By the way, to help get you started on those suggestions you can do this:

1. Change the podcast episode's markdown file to fix the 2nd typo
2. Run a `git commit --amend`
3. Change the commit message to `Change nuisances to nuances`
4. Push your changes to fork with `git push origin master --force`

Once that's been verified to be good to go I'll merge it in.

**Comment by dancingpixels** [comment]
I was about opening a new pull request as I don't have a access to a terminal. But I'd  give your suggestion a go. Many thanks.

**Comment by nickjj** [comment]
Thanks, can you also address step 4 from the previous reply?

The commit message is still using "Changed" instead of "Change" as the first word.

**Comment by nickjj** [comment]
Thanks, it's live on the site now.

**Pull request merged**
