### PR TITLE
Update to a custom html5 audio

### PR DESCRIPTION
**Pull request by alexdsmartins**
As detailed on issue #1 a custom htmll5 audio was required.
This implementation adds a new html5 snipped that is included in the template.

Currently, the material icons library is included in the `base.html` but will be removed when the SVGs are extracted from the library. I already did some work extracting the SVGs but I could not specify the correct path for the files using `jekyll-assets`.

### CODE REVIEW

**Comment by nickjj** [comment]
Hi,

What happens if you put the svgs in `images/player/foo.svg` and then referenced that path? You should be able to use the `background-image: asset_url('images/player/foo.svg')` helper in the SCSS. That should resolve back to the correct path.

**Comment by alexdsmartins** [comment]
Hi,
I already removed the Material Icon dependency. It should now fulfil all the basic requirements.

**Comment by nickjj** [comment]
Thanks.

I started to play around with it locally today and I noticed a few issues. I'm not 100% sure if this is isolated to Jekyll serving the mp3s (I know I had trouble with this in the past) but:

On Chrome if you copy the current time stamp, you end up with a syntactically correct URL but when I paste it into a new tab, the player doesn't jump to that specific point in the bar but it does with FireFox.

Also on Edge and IE 11 nothing works with or without the time stamp in the URL. When you click play, nothing happens and none of the controls react to input. Although on Edge it does load the time stamp from the URL, where as on IE 11 that doesn't happen.

In Edge it throws an exception with `SCRIPT438: SCRIPT438: Object doesn't support property or method 'composedPath'` which points to L215 in `main.js`. In IE 11 no errors are shown in the console.

**Comment by alexdsmartins** [comment]
I already implemented the changes required to make the player work on IE and Edge. But right now I am not able to run it on Chrome. For some reason, the mp3s are not loading. I beginning to wonder if chrome does not like the mp3 files served by Jekyll. Can you have a look at this?

**Comment by nickjj** [comment]
Thanks!

Yeah it seems to be really sketchy when it comes to locally playing back mp3s with Jekyll's built in web server. I've had very hit and miss results in both Chrome and FF even with the default audio player. Sometimes it works, sometimes it doesn't.

I think I'll have to deploy the site to a local VM so I can test it with nginx.

I do appreciate the work you've put into this PR. I will run that VM test over the weekend.

**Comment by alexdsmartins** [comment]
You're welcome. If possible make the whole setup work on docker to ease the development. I also changed the code to work on my default settings of ESLint and Prettier but feel free to change the code as needed or to enforce some rule.

**Comment by nickjj** [comment]
I would love to Dockerizer Jekyll but unfortunately live reload doesn't work when Jekyll is running in a container (at least not with Docker for Windows), and I had all sorts of issues related to resolving URLs.

But I did just quickly spin up an nginx container to serve the `_sites/` directory, and funny enough it had the same issues as with Jekyll's web server. Keep in mind I wasn't even proxying Jekyll's web server. I just told nginx to serve a directory of static files.

I wonder if there's some browser policy that's preventing audio from working over localhost.

Do you get the same results?

1. Create a `default.conf` in the root directory of this repo with this content:

```nginx
server {
  listen 80;

  server_name _;
  root /app/_site;

  index index.html;

  location / {
    try_files $uri $uri.html $uri/ =404;
  }
}
```

2. Run this command:

```
docker run --rm -it -p 80:80 -v "${PWD}":/app \
  -v "${PWD}"/default.conf:/etc/nginx/conf.d/default.conf nginx
```

Head over to http://localhost in your browser.

**Comment by alexdsmartins** [comment]
For me it worked after I changed in `_config.dev.yml`
```
url: "http://localhost:80"
mp3_url_path: "http://localhost:80/assets/podcast/running-in-production-"
```
I then generated the website and ran your instructions. On Chrome the behaviour I now the same of  Firefox. I read somewhere when searching for a solution for our problem that it could be because Chrome only reads html5 audio from servers that support HTTP persistent connection.

**Comment by nickjj** [comment]
Oh nice catch I forgot about those settings.

After changing those it's working for me too, and it's quite nice because if you make a change to a file, it still gets picked up. You just need to manually reload the page instead of using live reload.

Also just a heads up, you can change those URLs to `http://localhost` and it continues to work. The `:80` is the default port for HTTP so browsers work without defining it explicitly.

**Comment by alexdsmartins** [comment]
Great. :+1:  Feel free to do some additional testing on the player and point out anything that is not working as indented. Also, I was planning to release the player as a separated project for anyone that needs an implementation of a audio player that supports timestamping.

**Comment by nickjj** [comment]
As a preliminary test, things are looking good.

- Under Windows 10 stable it's working in Chrome stable, FF stable, MS edge and IE 11.
- I will be able to test Linux (Ubuntu) later today with Chrome, Chromium and FF too.

**What OS are you using, and what browsers are you able to test it against?**

Also I made a couple of adjustments to your script and styles. It might be easiest for you to just commit those in and @nickjj me in the commit.

**Here's a screenshot of what it looks like after my changes:**

image

**Notable changes:**

- The background color now matches the page's background and profile bio background color
- There's a bit of spacing around the volume (IMO it looks cleaner and it's easy to drag around)
- The tooltip for copying the time happens on hovering over the icon instead of the playback time
- The speed toggle jumps in 0.25x increments

**Javascript changes (just the diff):**

```javascript
      case 1.0:
        audio.playbackRate = 1.25;
        span.innerHTML = "&times;1.25";
        break;
      case 1.25:
        audio.playbackRate = 1.5;
        span.innerHTML = "&times;1.50";
        break;
      case 1.5:
        audio.playbackRate = 1.75;
        span.innerHTML = "&times;1.75";
        break;
      case 1.75:
        audio.playbackRate = 2.0;
        span.innerHTML = "&times;2.00";
        break;
      case 2.0:
        audio.playbackRate = 0.75;
        span.innerHTML = "&times;0.75";
        break;
      case 0.75:
        audio.playbackRate = 1.0;
        span.innerHTML = "&times;1.00";
        break;
      default:
        audio.playbackRate = 1.0;
        span.innerHTML = "&times;1.00";
```

**New SCSS file:**

I mostly used SCSS variables instead of hard coded colors. You may want to diff this locally.

```scss
audio {
  display: block;
  width: 100%;
}

@media screen and (max-width: 400px) {
  .hidden-mobile {
    display: none !important;
  }
}

.audio-player {
  background-color: $gray-100;
  padding-top: 10px;
  margin-top: 10px;
  margin-bottom: 50px;
  border-radius: 3px;
  border: 1px solid $gray-300;
  position: relative;
  user-select: none;
  color: $gray-900;
}

.controls {
  display: flex;
  flex-wrap: wrap;
  padding: 1px;
}

.controls button {
  font-size: 14px;
  padding: 8px 3px;
  border: 0;
  background-color: transparent;
  color: inherit;
  font-size: inherit;
  line-height: inherit;
  display: inline-flex;
  align-items: center;
}

.left-controls {
  display: flex;
  flex-grow: 1;
  align-items: center;
}

.right-controls {
  display: flex;
  align-items: center;
  flex-wrap: wrap;
}

.audio-player-icon {
  width: 24px;
  height: 24px;
  display: inline-block;
  background-repeat: no-repeat;
}

.icon-playarrow {
  background-image: asset_url('audioplayer/play_arrow.svg');
}

.icon-pause {
  background-image: asset_url('audioplayer/pause.svg');
}

.icon-filecopy {
  width: 16px;
  height: 16px;
  background-size: 16px 16px;
  background-image: asset_url('audioplayer/file_copy.svg');
}

.icon-fastforward {
  background-image: asset_url('audioplayer/fast_forward.svg');
}

.icon-volumeup {
  background-image: asset_url('audioplayer/volume_up.svg');
}

.icon-volumedown {
  background-image: asset_url('audioplayer/volume_down.svg');
}

.icon-volumeoff {
  background-image: asset_url('audioplayer/volume_off.svg');
}

.progress-slider-background {
  background-color: lighten($primary, 60%);
  cursor: pointer;
  padding-right: 7px;
  box-sizing: border-box;
  margin-left: 10px;
  margin-right: 10px;
  margin-bottom: 10px;
}

.progress-slider {
  position: relative;
  pointer-events: none;
  background-color: $primary;
  height: 8px;
  margin-left: 0;
  margin-right: 0;
  width: 0%;
  padding-left: 7px;
  box-sizing: border-box;
}

.progress-slider::after {
  content: "";
  position: absolute;
  right: 0;
  top: 50%;
  transform: translate(50%, -50%);
  display: block;
  width: 14px;
  height: 14px;
  background-color: $primary;
  border-radius: 50%;
  z-index: 1;
  box-shadow: 0 0 3px rgba(0, 0, 0, 0.5);
}

.playback-time {
  font-family: "Roboto", sans-serif;
  margin-right: 2px;
  margin-top: 2px;
  font-size: 12px;
}

.playback-time-highlight {
  color: $primary;
}

.volume-group {
  display: flex;
  flex-grow: 0;
  align-items: center;
}

.volume-slider-background {
  cursor: pointer;
  display: inline-block;
  width: 50px;
  background-color: lighten($primary, 60%);
  margin-left: 0;
  margin-bottom: 1px;
  margin-right: 16px;
}

.volume-slider {
  pointer-events: none;
  position: relative;
  height: 6px;
  width: 100%;
  background-color: $primary;
}

.volume-slider::after {
  content: "";
  position: absolute;
  right: 0;
  top: 50%;
  transform: translate(50%, -50%);
  display: block;
  width: 12px;
  height: 12px;
  background-color: $primary;
  border-radius: 50%;
  z-index: 1;
  box-shadow: 0 0 3px rgba(0, 0, 0, 0.5);
}

.audio-player button {
  cursor: pointer;
  margin-right: 3px;
  vertical-align: middle;
  position: relative;
}

.controls .replay-button {
  margin-right: 0px;
}

.speed-text {
  font-family: "Roboto", sans-serif;
  font-size: 12px;
}

.copy-msg {
  font-size: 13px;
  font-family: "Roboto", sans-serif;
  opacity: 0;
  transition: opacity 0.5s ease-out;
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  background-color: $primary;
  color: $white;
  border-radius: 3px;
  box-shadow: 0 0 3px rgba(0, 0, 0, 0.5);
  padding: 2px 6px;
  z-index: 1;
  text-align: center;
  pointer-events: none;
}
```

**Pending concerns:**

What do you think about everything listed below?

I started a Twitter poll to see if people on smart phones typically use native podcast apps or their browser. At 24 votes, 87.5% are using a native app.

That's a lot of native app usage but I wonder how we can maybe fit the playback speed in mobile form, even if it means maybe hiding the copy time stamp icon as a compromise.

Another concern as I have is with the above screenshot in its normal form, is it worth making the volume control a little wider by default so it's easier to fine tune the volume? It doesn't need to be crazy wide, but what about twice as wide or 25% wider? Would that throw off the balance?

Are we using the best possible font face for the controls that's widely available on all / most devices?

Mobile view is still a bit sketchy looking. For example here's a screenshot with a Pixel 2 when using Chrome's dev tools to make it that size:

image

**Comment by alexdsmartins** [comment]
Feel free to commit any change to enhance the style of the web player and make suitable in your website directly to this branch.
#### Testing
I am running Ubuntu on this machine so I can test Firefox, Chrome and Chromium natively. I also can test IE and Edge on a VM.
#### Mobile devices:
Regarding the use on a mobile device, I think it is more important to keep the control bar in one line and hide the copy time stamp and then the playback speed. Most people, especially the target audience of this podcast. will use a dedicated app for listening to the podcast on mobile. I also used Chrome dev tools to test the design on different form factors And got it working on all the devices on the default list.

The only edge case is when I resize the manually the window an the sidebar change size. Please see the picture below:
image

**Comment by nickjj** [comment]
I wonder why it wraps so differently when I test your branch with my super minor modifications.

I'm up for hiding the copy times icon and bringing back the speed control if you can get it to fit on 1 line on all mobile devices.

**Comment by alexdsmartins** [comment]
Please see the changes made. I don't think there is much more to do without changing the interface for mobile devices.

**Comment by nickjj** [comment]
Yep, although I'd consider making those mobile classes a bit more human friendly.

Such as changing `hidden-mobile1` to `hidden-mobile-370px` or `hidden-mobile-xs` and then doing the same for the 2 and 3 variants.

**Comment by alexdsmartins** [comment]
Done. But for some reason using SCSS variables the styles are not displayed properly. See image below:
image

**Comment by nickjj** [comment]
It looks like you added some type of funky character into the SCSS that prevented it from being loaded.

GitHub is stripping it out from its display but the very last line of this snippet of the SCSS file has some type of invisible character that Vim is identifying as `<200b>`. After I removed it then the styles worked.

```scss
@media (max-width:765px) and (min-width:576px) {
  .hidden-mobile-765px-576px {
    display: none !important;
  }
}​
```

Although now I'm seeing another problem where if I click the show notes time stamps, it's not jumping to the correct time in the player. There's no JS errors either.

**Comment by alexdsmartins** [comment]
Thanks for pointing that out. It is now fixed.

**Comment by nickjj** [comment]
On L117 of the newest player's commit, you are referencing jQuery with `audio.currentTime = $(this).data("audio-seek");`. Is that intended?

**Comment by alexdsmartins** [comment]
No, it wasn't. It was a snipped I copied from your implementation. It is now in plain javascript.

**Comment by nickjj** [comment]
Now that we're getting closer to feature complete, I quickly looked through the JS.

In a lot of spots you're doing ` if (foo === true)` conditional checks. That can be simplified to `if (foo)` right, or is the explicit `===` doing something extra?

**Comment by alexdsmartins** [comment]
In most cases, it can be simplified. The triple equals do a type check between the two variables. For example:
1==true   // returns true
1===true // returns false
In this code is does matter because for example `isLoaded` is always a boolean and the type check is not required.

**Comment by alexdsmartins** [comment]
Hi. I clean up the code and improved the player in several areas:
- Improve compatibility with IE;
- Add a loading spinner when metadata is been fetch or audio is seeking;
- Fix the volume icon to change when we click the volume bar;
- Only setting the current time once when loading from a timestamp or from local storage.

**Comment by nickjj** [comment]
Nice, I'm going to give it an extensive test.

Right off the bat I noticed something tho. This wasn't discussed initially but it would be very nice if we could save the player's volume and speed settings in local storage and then pull in from that with a default of 100% volume and 1x speed if it's not yet saved.

This way user's don't need to keep resetting them on each page visit. I immediately noticed that after opening a new tab a few times.

**Comment by nickjj** [comment]
Here's what I found after doing a first pass:

---

## Bugs

### JS error related to querySelector being null

1. Goto a specific podcast page
2. Click the logo to goto the home page
3. Check the devs tool console for the exact JS error

The pattern seems to be associated to navigating to any page that doesn't have the player on the page. This happens when transitioning between pages with Turbolinks or doing a full page reload.

### NaN:NaN / 00:00 time readout in a missing / unplayed mp3 scenario

1. Rename one of the mp3 files to be mp3_ so that it's missing
2. Check the player's time readout

This happens when the mp3 isn't found. Perhaps it could default to 00:00 / 00:00 or even better 0:00 / 0:00 so it matches the default defined in the player's HTML (I would go for this).

This also happens when viewing a new mp3 that hasn't yet had a value saved to local storage. You can test this by clearing your local storage. Every mp3 (even valid ones) will report NaN:NaN until you play it.

This makes me believe it's more than just a display bug when a file is missing.

## UI / Behavior issues

### HTML title for the copy time action doesn't match the element it's on

Currently you have an HTML title on the span that shows the 0:00 / 0:00 to mention clicking it to copy the current time, but this functionality is associated to the copy icon not the time label.

I moved the title to the button that controls that behavior, since that behavior only occcurs on the button.

### Player doesn't have the volume and playback speed in local storage

This wasn't discussed initially but it would be very nice if we could save the player's volume and speed settings in local storage and then pull in from that with a default of 100% volume and 1x speed if it's not yet saved.

## Code changes 

Changed the wording of the copy title and moved the title from the playback-time span to the filecopy button:

```html
      <button class="js-copy-time hidden-mobile-410px hidden-mobile-765px-576px"
              title="Click to copy current time">
        <i class="audio-player-icon icon-filecopy"></i>
      </button>
```


Moved the inline style to set display none in a class:

```html
      <span class="js-copy-msg copy-msg">
        Copied URL with current time.
      </span>
```

```scss
.copy-msg {
  display: none;
  // ...

```

In the player's HTML, I changed `copied url with current time.` to `copied URL with current time.`.

## Manual testing process

- Load the player on a fresh full reload to avoid Turbolinks
- Load the player after a page transition to have Turbolinks take effect
- Load the player when local storage has no saved time
- Load the player when local storage has a saved time

- Look at the player at various resolutions using a browser's dev tools' devices
  - Ensure everything is visible and positioned correctly on larger devices
  - Ensure everything but the copy time button is visible and positioned correctly on the smallest devices
  - Ensure it looks presentable at non-standard resolutions
  - Ensure all tooltips are positioned and fit on all devices

- Slide around the seeker
  - Ensure the seeker hits the left and right edges of its region
  - Ensure the time label shows the correct values based on the seeker being at 0 or the end
  - Ensure the time label shows the correct values based on the seeker being anywhere in the middle
  - Ensure the seeker jumps back to the beginning after it reaches the end
  - Ensure violently sliding things around like a manic doesn't break anything

- Click the play / pause toggle
  - Ensure the audio starts and stops
  - Ensure the icons switch when clicking it
  - Ensure it doesn't break when spam clicking it as fast as possible

- Click the time label
  - Ensure nothing happens while something is playing
  - Ensure nothing happens while nothing is playing

- Click the copy time button
  - Ensure the correct time gets copied to the clipboard
  - Ensure the message shows up and disappears on all device resolutions
  - Ensure it doesn't break when spam clicking it as fast as possible

- Click the playback speed button
  - Ensure it cycles from 0.75x to 2x in 0.25x intervals
  - Ensure the speed changes while an mp3 is playing
  - Ensure the new speed takes effect after unpausing the mp3
  - Ensure it doesn't break when spam clicking it as fast as possible

- Click the volume mute toggle button
  - Ensure the volume is muted when playing an mp3
  - Ensure when reverting from muted the volume slider goes back to where it was
  - Ensure the icon changes to muted and back to normal when being toggled
  - Ensure if the volume control was set to minimum, toggling gives you some amount of volume
  - Ensure it doesn't break when spam clicking it as fast as possible

- Slide around the volume control
  - Ensure a playing mp3 has its volume adjusted
  - Ensure a paused mp3 doesn't throw errors
  - Ensure a paused mp3 that gets played starts with the new volume when changed
  - Ensure the icon changes based on the loudness
  - Ensure sliding to the minimum amount results in the audio being muted
  - Ensure sliding to the minimum amount results in the icon showing it's muted
  - Ensure violently sliding things around like a manic doesn't break anything

- Click empty areas of the player
  - Ensure nothings happens
  - Ensure nothing breaks

### Browser passing results

If a browser is listed below, it means I performed the manual testing process and everything works based on the above tests, minus the known bugs.

#### Windows 10

- Chrome 79 (latest stable as of Jan. 11th 202)
- FireFox 72 (latest stable of Jan. 11th 2020)
- Microsft Edge (whatever version comes with Windows 10 stable)
- Internet Explorer 11

---

If you can perform the same tests on whatever OS / browsers / mobile devices you have that would be great.

**Comment by alexdsmartins** [comment]
I reviewed your comments and addressed all the bugs you have found. I also implemented the new requested feature of storing the volume and playback rate on local storage.
I ran the test procedure you suggested and also added new test cases.
## New test cases
- Ensure player loads with correct time when loading from a timestamp
  - Timestamp in mm:ss format
  - Timestamp in hh:mm:ss format
- Ensure player loads with correct time when loading from a bookmark
- Ensure when loading metadata or when seeking to a new position the loading spinner is shown and play/pause buttons are hidden
- Ensure that if playback speed is stored on local storage it is properly retrieved when loading new mp3
  - The playback Speed indicator is correct
  - Audio playback rate property is correct
- Ensure that if the volume is stored on local storage it is properly retrieved when loading new mp3
  - The volume bar is correct
  - The volume icon is correct
  - Audio volume and the audio muted property is loaded

### Tested on:
Windows 10:
  - Firefox 72
  - Chrome 79
  - IE 11
  - Opera 66

Android: 
  - Chrome 79 
  - Firefox 68
  - Samsung Internet 10

**Comment by nickjj** [comment]
Couple of things I noticed:

- You have (2) `style="display:none"` declarations in the `audio-player.html`. I'm using Bootstrap v4 so I replaced those with a `d-none` class on the same element but now those icons are completely gone, so maybe something is happening at the JS level that's abnormal?

- For shows that are 1 hour+, can we kill off the leading `00:` on the left side of the time label? For example instead of `00:12:24 / 01:24:28` can we have `12:24 / 01:24:28`?

**Pull request closed without merging**
